In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("sms.csv")

In [3]:
data.shape

(500, 2)

In [4]:
data.head(5)

  label                                               text
0   ham  Hey RAV!! Are we still meeting @ 6pm today??? ...
1  spam  CONGRATULATIONS!!! You have WON a FREE iPhone ...
2   ham  Rose, can you pls send me the project report b...
3  spam  URGENT!!! Your bank account is suspended!!! Ve...
4   ham  Hey!!! I'm running late today :( Traffic is cr...

In [5]:
import spacy

In [6]:
nlp = spacy.load("en_core_web_trf")

In [7]:
doc = nlp(data["text"][0])

In [9]:
for token in doc:
    print (token.text)

Hey
RAV
!
!
Are
we
still
meeting
@
6
pm
today
?
?
?
I
will
bring
the
documents
&
laptop
.
Let
me
know
ASAP
!
!

In [10]:
len(doc)

29

In [15]:
def dataprocessing(text):
    doc = nlp(text)
    tokens = []
    for token in doc:
        if token.is_stop:
            continue
        if token.is_punct:
            continue
        tokens.append(token.lemma_.lower())
    return " ".join(tokens)

In [16]:
response = dataprocessing(data["text"][0])

In [17]:
response

'hey rav meet 6 pm today bring document laptop let know asap'

In [18]:
data["text"][0]

'Hey RAV!! Are we still meeting @ 6pm today??? I will bring the documents & laptop. Let me know ASAP!!'

In [20]:
data['text'] = data["text"].apply(dataprocessing)

In [21]:
data.head(5)

  label                                               text
0   ham  hey rav meet 6 pm today bring document laptop ...
1  spam  congratulation win free iphone 15 worth $ 999 ...
2   ham  rose pls send project report 5 pm need review ...
3  spam  urgent bank account suspend verify immediately...
4   ham  hey run late today traffic crazyyyy reach offi...

In [23]:
X = data['text']
Y = data['label']

In [22]:
from sklearn.model_selection import train_test_split

In [24]:
 x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.4, random_state=2)

In [25]:
x_train.shape

(300,)

In [26]:
y_train.shape

(300,)

In [27]:
x_test.shape

(200,)

In [28]:
y_test.shape

(200,)

In [29]:
x_train.head(5)

99                 forget gym session today evening 7 pm
235         mobile number select free data pack dial 999
418    dear customer atm card deactivate update kyc d...
112    hey run late today traffic crazyyyy reach offi...
398    share nlp lecture slide today class miss 20 mi...
Name: text, dtype: object

In [43]:
!python3 -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl (400.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 9.7 MB/s  0:00:430:00:0100:02
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.8.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')

In [44]:
nlp = spacy.load('en_core_web_lg')

In [81]:
x_train.shape

(300,)

In [82]:
y_train.shape

(300,)

In [83]:
x_train

99                 forget gym session today evening 7 pm
235         mobile number select free data pack dial 999
418    dear customer atm card deactivate update kyc d...
112    hey run late today traffic crazyyyy reach offi...
398    share nlp lecture slide today class miss 20 mi...
                             ...
22       plan start model training tonight clean dataset
72                 forget gym session today evening 7 pm
493             congratulation win free shopping voucher
15     hot single area click http://datingnow.com sta...
168    hi rose thank help yesterday nlp assignment ap...
Name: text, Length: 300, dtype: object

In [84]:
y_train

99      ham
235    spam
418    spam
112     ham
398     ham
       ...
22      ham
72      ham
493    spam
15     spam
168     ham
Name: label, Length: 300, dtype: object

In [45]:
def embedding(text):
    doc = nlp(text)
    return doc.vector

In [85]:
x_train_vec = x_train.apply(embedding)
y_train_vec = y_train.apply(embedding)

In [86]:
x_train_vec

99     [0.044020716, 0.35438544, 0.15177001, 0.203184...
235    [-0.00038287695, 0.120944746, 0.05572188, 0.15...
418    [-0.18039209, 0.10218929, -0.2162617, -0.01151...
112    [-0.005584333, 0.24865848, -0.14559533, -0.029...
398    [-0.04648989, 0.335526, 0.10679533, 0.30777377...
                             ...
22     [0.055190712, 0.10034101, -0.11663602, 0.03420...
72     [0.044020716, 0.35438544, 0.15177001, 0.203184...
493    [-0.1189006, -0.0507796, -0.0070379972, -0.062...
15     [0.1334065, 0.11203565, -0.23554264, 0.2113526...
168    [-0.12497645, 0.28882998, -0.22102751, 0.05354...
Name: text, Length: 300, dtype: object

In [87]:
y_train_vec

99     [-0.77332, -0.28254, 0.58076, 0.84148, 0.25854...
235    [-1.0007, 0.17415, -0.39966, -0.41048, -0.8321...
418    [-1.0007, 0.17415, -0.39966, -0.41048, -0.8321...
112    [-0.77332, -0.28254, 0.58076, 0.84148, 0.25854...
398    [-0.77332, -0.28254, 0.58076, 0.84148, 0.25854...
                             ...
22     [-0.77332, -0.28254, 0.58076, 0.84148, 0.25854...
72     [-0.77332, -0.28254, 0.58076, 0.84148, 0.25854...
493    [-1.0007, 0.17415, -0.39966, -0.41048, -0.8321...
15     [-1.0007, 0.17415, -0.39966, -0.41048, -0.8321...
168    [-0.77332, -0.28254, 0.58076, 0.84148, 0.25854...
Name: label, Length: 300, dtype: object

In [88]:
x_train_vec.shape

(300,)

In [89]:
y_train_vec.shape

(300,)

In [96]:
y_df = y_train_vec.to_frame()
x_df = x_train_vec.to_frame()

In [97]:
from sklearn.svm import LinearSVC

In [98]:
model = LinearSVC()

In [99]:
model.fit(x_df,y_df)

ValueError: setting an array element with a sequence.